# Generated by Django 3.1.4 on 2020-12-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201220_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='nice',
            new_name='favs',
        ),
    ]
