# Generated by Django 3.1.4 on 2020-12-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favs', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favlist',
            name='posts',
            field=models.ManyToManyField(related_name='fav_lists', to='posts.Post'),
        ),
    ]
