# Generated by Django 3.1.4 on 2020-12-20 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favs', '0003_favlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favlist',
            old_name='post',
            new_name='posts',
        ),
    ]
