# Generated by Django 3.1.4 on 2020-12-21 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('followers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followerlist',
            name='following_list',
            field=models.ManyToManyField(blank=True, related_name='following_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followerlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followedlist',
            name='followed_list',
            field=models.ManyToManyField(blank=True, related_name='followed_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followedlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
