# Generated by Django 3.1.4 on 2020-12-20 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0002_auto_20201220_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followedlist',
            name='followed_list',
            field=models.ManyToManyField(blank=True, related_name='followed_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followerlist',
            name='following_list',
            field=models.ManyToManyField(blank=True, related_name='following_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
